#!/usr/bin/env bash
#  Bash script that configures a new Ubuntu machine to HAproxy
apt-get update
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get -y install haproxy=2.0.\*
echo "frontend load-banlancer
    bind *:80
    mode http
    default_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo "backend web-backend
    balance roundrobin
    server 2050-web-01 34.229.218.206:80 check
    server 2050-web-02 54.210.76.219:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
